### ISSUE TITLE
Every fenced code block in markdown files gets checked

### ISSUE THREAD

**Issue by dvdvgt** [effekt-lang/effekt-vscode#11]
# Problem

The extension tries to check every fenced code block in markdown files, regardless of the actual language the block contains.

# How to reproduce

Create an arbitrary markdown file (e.g. `text.md`) and create an arbitrary fenced block within it, e.g.

\`\`\`
const x = 1
\`\`\`

here the following linting error is given

> string matching regex '//[^\n]*(\n|\z)' expected but 'c' found

# Possible solution

Instead of the extension being triggered by every fenced code block in every markdown file, make the extension only sensitive to files with the file extension `.effekt.md`. This should be specific enough for it not being triggered by accident.

**Comment by JonathanStarup** [comment]
I had the same issue. Other possible solutions:
* Add the option to disable md parsing to its easy to toggle when you need it, this one seems like a nice minimum solution
* Only trigger parsing on code blocks with '''effect ''' since that's also used to trigger highlighting in github
  * An even milder version of this where no existing effekt md files need change is to parse code in all blocks, except those tagged with other languages
* Have a markdown header, i know github supports HTML comments (\)

**Comment by jiribenes** [comment]
This is resolved as of #14.
In order to use literate markdown files, one must always specify the `.effekt.md` extension.
